#!/bin/sh
# Export, sign and upload archives that were compiled on a released macOS.
#
# The developer Mac runs a macOS beta, so archives built here record a beta
# BuildMachineOSBuild and App Store Connect rejects them with ITMS-90111. CI
# (.github/workflows/safari-archive.yml or codemagic.yaml) compiles on a
# released macOS instead, signing ad hoc. This script does the half that needs
# the real distribution identity, which only exists on this Mac.
#
# Signing runs after compilation, so it does not alter DTXcode, DTSDKName or
# BuildMachineOSBuild — the metadata App Review actually inspects.
#
#   safari/upload-ci-archives.sh <dir-with-unpacked-xcarchives> [--export-only]
#
# The directory must contain EarnDark-iOS.xcarchive and
# EarnDark-macOS.xcarchive. Pass --export-only to stop after producing signed
# packages locally, without sending anything to Apple. Set PLATFORMS to do just
# one side, e.g. PLATFORMS=macOS when the other has already been accepted and
# would be refused as a duplicate build number.
set -eu

DIR=${1:?usage: safari/upload-ci-archives.sh <dir-with-xcarchives> [--export-only]}
MODE=${2:-upload}
PLATFORMS=${PLATFORMS:-"iOS macOS"}

ROOT=$(cd "$(dirname "$0")/.." && pwd)

# The release toolchain, not the beta that xcode-select points at. Only used to
# drive export here; it does not re-run the compiler.
DEVELOPER_DIR=${DEVELOPER_DIR:-/Applications/Xcode.app/Contents/Developer}
export DEVELOPER_DIR

case "$MODE" in
  --export-only) PLIST="$ROOT/safari/ExportOptions.plist"; VERB="exported" ;;
  upload)        PLIST="$ROOT/safari/UploadOptions.plist"; VERB="uploaded" ;;
  *) echo "unknown mode: $MODE" >&2; exit 2 ;;
esac

for platform in $PLATFORMS; do
  archive="$DIR/EarnDark-$platform.xcarchive"
  [ -d "$archive" ] || { echo "missing $archive" >&2; exit 1; }

  case "$platform" in
    iOS)   app="$archive/Products/Applications/Superteam Earn Dark.app"; plist="$app/Info.plist" ;;
    macOS) app="$archive/Products/Applications/Superteam Earn Dark.app"; plist="$app/Contents/Info.plist" ;;
  esac

  host=$(/usr/libexec/PlistBuddy -c 'Print :BuildMachineOSBuild' "$plist")
  version=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$plist")
  build=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$plist")
  sdk=$(/usr/libexec/PlistBuddy -c 'Print :DTSDKName' "$plist")

  # Refuse an archive that came off a beta host — the whole failure this script
  # exists to avoid, and cheap to catch before a rejected upload burns the
  # build number. Beta seeds carry a five-digit build with a 5 in the thousands
  # place (26A5388g); released builds do not (25F80, 26A350).
  case "$host" in
    *A5[0-9][0-9][0-9]*|*B5[0-9][0-9][0-9]*|*C5[0-9][0-9][0-9]*)
      echo "$platform: BuildMachineOSBuild $host looks like a macOS beta." >&2
      echo "Archive it on CI instead; App Review rejects these (ITMS-90111)." >&2
      exit 1 ;;
  esac

  # The macOS targets set ENABLE_APP_SANDBOX, and those entitlements are
  # generated by the signing step rather than living in a checked-in file. An
  # archive built with signing disabled therefore has none, and App Store
  # Connect refuses the upload with error 90296 — after the iOS half has
  # already gone through, which is a messy place to find out.
  if [ "$platform" = macOS ]; then
    if ! codesign -d --entitlements - --xml "$app" 2>/dev/null | grep -q 'com.apple.security.app-sandbox'; then
      echo "$platform: no app-sandbox entitlement in the archive." >&2
      echo "CI must archive ad hoc (CODE_SIGN_IDENTITY=-), not unsigned." >&2
      exit 1
    fi
  fi

  echo "$platform: $version ($build), $sdk, host $host"

  rm -rf "$DIR/out-$platform"
  log="$DIR/export-$platform.log"
  if xcodebuild -exportArchive \
       -archivePath "$archive" \
       -exportPath "$DIR/out-$platform" \
       -exportOptionsPlist "$PLIST" >"$log" 2>&1; then
    echo "$platform: $VERB"
  else
    echo "$platform: FAILED — see $log" >&2
    grep -E '^error:|error: exportArchive|The server.s response' "$log" | head -5 >&2
    exit 1
  fi
done
